version: "3.7"

services:
  snowflake:
    image: "registry.cn-shanghai.aliyuncs.com/yingzhor/snowflake:1.1.0"
    container_name: "snowflake"
    restart: "always"
    ports:
      - "8080:8080"
    environment:
      - "SNOWFLAKE_NODE_ID=0"
      - "SNOWFLAKE_HTTP_PORT=8080"
      - "SNOWFLAKE_INDENT=false"
