version: "3.7"

services:
  snowflake:
    image: "registry.cn-shanghai.aliyuncs.com/yingzhor/snowflake:latest"
    container_name: "snowflake"
    restart: "always"
    ports:
      - "8080:8080"
    command:
      - "docker-entrypoint"
      - "--node-id=0"
      - "--response-type=protobuf"
