# ----------------------------------------------------------------------------------------------------------------------
# snowflake and kubernetes
#   https://github.com/yingzhuo/snowflake
# ----------------------------------------------------------------------------------------------------------------------

apiVersion: v1
kind: Namespace
metadata:
  name: snowflake

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-0
  namespace: snowflake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowflake
  template:
    metadata:
      labels:
        app: snowflake
    spec:
      restartPolicy: Always
      containers:
        - name: snowflake
          image: quay.io/yingzhuo/snowflake:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: http
              path: "/healthz"
              scheme: HTTP
          command:
            - "snowflake"
            - "--node-id=100"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-1
  namespace: snowflake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowflake
  template:
    metadata:
      labels:
        app: snowflake
    spec:
      restartPolicy: Always
      containers:
        - name: snowflake
          image: quay.io/yingzhuo/snowflake:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: http
              path: "/healthz"
              scheme: HTTP
          command:
            - "snowflake"
            - "--node-id=101"
---

apiVersion: v1
kind: Service
metadata:
  name: snowflake
  namespace: snowflake
spec:
  selector:
    app: snowflake
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
