# ----------------------------------------------------------------------------------------------------------------------
# snowflake and kubernetes
#   https://github.com/yingzhuo/snowflake
# ----------------------------------------------------------------------------------------------------------------------

apiVersion: v1
kind: Namespace
metadata:
  name: snowflake

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-0
  namespace: snowflake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowflake
  template:
    metadata:
      labels:
        app: snowflake
    spec:
      restartPolicy: Always
      containers:
        - name: snowflake
          image: "registry.cn-shanghai.aliyuncs.com/yingzhor/snowflake:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 3
            httpGet:
              port: 8080
              path: "/ping"
              scheme: HTTP
          command:
            - snowflake
            - --http-port=8080
            - --node-id=0
            - --type=protobuf
            - --indent=true
            - --quiet=false
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-1
  namespace: snowflake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowflake
  template:
    metadata:
      labels:
        app: snowflake
    spec:
      restartPolicy: Always
      containers:
        - name: snowflake
          image: "registry.cn-shanghai.aliyuncs.com/yingzhor/snowflake:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 3
            httpGet:
              port: 8080
              path: "/ping"
              scheme: HTTP
          command:
            - snowflake
            - --http-port=8080
            - --node-id=1
            - --type=protobuf
            - --indent=true
            - --quiet=false
---

apiVersion: v1
kind: Service
metadata:
  name: snowflake
  namespace: snowflake
  annotations:
    com.github.yingzhuo/created-by: "yingzhuo"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: snowflake
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
