# ----------------------------------------------------------------------------------------------------------------------
# snowflake and kubernetes
#   https://github.com/yingzhuo/snowflake
# ----------------------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: snowflake
  annotations:
    istio-injection: enabled
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-0
  namespace: snowflake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowflake
  template:
    metadata:
      labels:
        app: snowflake
    spec:
      restartPolicy: Always
      containers:
        - name: snowflake
          image: "registry.cn-shanghai.aliyuncs.com/yingzhor/snowflake"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 3
            httpGet:
              scheme: HTTP
              port: 8080
              path: "/ping"
          env:
            - name: SNOWFLAKE_NODE_ID
              value: "0"
            - name: SNOWFLAKE_TYPE
              value: "json"
            - name: SNOWFLAKE_INDENT
              value: "true"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-1
  namespace: snowflake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowflake
  template:
    metadata:
      labels:
        app: snowflake
    spec:
      restartPolicy: Always
      containers:
        - name: snowflake
          image: "registry.cn-shanghai.aliyuncs.com/yingzhor/snowflake"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 3
            httpGet:
              scheme: HTTP
              port: 8080
              path: "/ping"
          env:
            - name: SNOWFLAKE_NODE_ID
              value: "1"
            - name: SNOWFLAKE_TYPE
              value: "json"
            - name: SNOWFLAKE_INDENT
              value: "true"
---

apiVersion: v1
kind: Service
metadata:
  name: snowflake
  namespace: snowflake
  annotations:
    com.github.yingzhuo/created-by: "yingzhuo"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: snowflake
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: snowflake
  namespace: snowflake
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: snowflake.k8s.io
      http:
        paths:
          - backend:
              serviceName: snowflake
              servicePort: 8080